/**
http://www.thai-language.com/ref/starred
https://docs.google.com/spreadsheets/d/1zgcZH80RBbUD4m3h43UAsPLY0LbhTMTnQvoawRyKg6E/edit?usp=sharing
(.*?)\t(.*?)$
{t:'$1'\t,e:'$2'},
**/
var thai1000 = [
{t:'ก็'	,e:'also; too; as well; well...; [suggestion] should...'},
{t:'ก็'	,e:'[a particle or conjunction that emphasizes that which follows]'},
{t:'กฎหมาย'	,e:'law'},
{t:'กร'	,e:'worker, laborer, doer, workman, [a suffix indicating] a person who... (does certain things), or an object that... (performs a certain function)'},
{t:'กรกฎาคม'	,e:'July'},
{t:'กรม'	,e:'[of government] a department'},
{t:'กรรม'	,e:'deed; kamma; karma; sin; bad karma earned'},
{t:'กรรมการ'	,e:'committee; board member'},
{t:'กระทำ'	,e:'to do; make; perform; carry out; act'},
{t:'กระนั้น'	,e:'in that way; like that'},
{t:'กระจาย'	,e:'to disperse; distribute; broadcast; spread; scatter'},
{t:'กระด้าง'	,e:'[is] harsh; stiff; rough; coarse; crude; obstinate; rebellious; mutinous'},
{t:'กระดาน'	,e:'board; plank; deal'},
{t:'กระดาน'	,e:'game board'},
{t:'กระดาษ'	,e:'paper'},
{t:'กระดูก'	,e:'bone'},
{t:'กระทรวง'	,e:'ministry'},
{t:'กระมัง'	,e:'likely as not, perhaps, maybe, probably'},
{t:'กรุง'	,e:'city, town, capital city'},
{t:'กรุงเทพฯ'	,e:'Bangkok, a province in central Thailand, having the largest provincial population, probably around 8 million (including metropolitan areas in surrounding provinces)'},
{t:'กลม'	,e:'[is] circular; round'},
{t:'กลับ'	,e:'to return or go back'},
{t:'กลัว'	,e:'[is] afraid (of); scared; frightened'},
{t:'กล้า'	,e:'brave; fearless; courageous'},
{t:'กลาง'	,e:'the middle; the center'},
{t:'กล่าว'	,e:'to speak; say; utter; tell or relate; to address; mention; declare'},
{t:'กว่า'	,e:'[suffix used for comparisons] than; more; -er'},
{t:'กว้าง'	,e:'[is] wide; broad'},
{t:'กษัตริย์'	,e:'[general] king'},
{t:'กสิกรรม'	,e:'agriculture'},
{t:'ก่อ'	,e:'to construct; to begin to build'},
{t:'ก่อน'	,e:'before; earlier; time gone by; prior to; in advance of; ahead of time; previously; formerly; initially; beforehand; firstly; now; ago'},
{t:'ก้อน'	,e:'lump; chunk; small rock; clump; ball; mass'},
{t:'กอบ'	,e:'to scoop up with the hands'},
{t:'กะ'	,e:'to; with; also'},
{t:'กะ'	,e:'to estimate or guess, to reckon, plan or plot'},
{t:'กะ'	,e:'guess; rough estimate'},
{t:'กัน'	,e:'together with'},
{t:'กันยายน'	,e:'September'},
{t:'กับ'	,e:'with; to; for'},
{t:'กา'	,e:'to make a check-mark, X or cross marks'},
{t:'กา'	,e:'teapot-kettle with a spout, tick, sign or mark set against an item'},
{t:'กาชาด'	,e:'a red cross'},
{t:'กาง'	,e:'to unfurl; to open; to stretch out; to spread out'},
{t:'กาย'	,e:'body; human body; physique'},
{t:'การ'	,e:'[placed before a verb or noun to create a noun which indicates a general activity, process, or state] the process of..., the activity of..., an enactment of..., the state of... [see notes]'},
{t:'กำไร'	,e:'profit; gain'},
{t:'กำลัง'	,e:'[auxiliary verb indicating the present participle, meaning "in the act of", similar to the English suffix, "-ing"]'},
{t:'กำหนด'	,e:'to schedule; set; limit; appoint; settle; condition; agree upon; assign; specify; define; establish'},
{t:'กำหนด'	,e:'a schedule or appointment'},
{t:'กิจ'	,e:'errand; duty; work; routine; affair; business'},
{t:'กิน'	,e:'to eat or drink; consume'},
{t:'กิริยา'	,e:'action; manners; behavior; conduct'},
{t:'กิเลส'	,e:'lust; evil wish; desire; longing; greed; avarice; rapacity'},
{t:'กี่'	,e:'how many'},
{t:'กุมภาพันธ์'	,e:'February'},
{t:'กุมาร'	,e:'infant; child; boy; young lad; son; prince'},
{t:'กู้'	,e:'to borrow [i.e. money] on interest'},
{t:'เกณฑ์'	,e:'criteria; criterion; formula; specification; standard'},
{t:'เก็บ'	,e:'to collect; preserve; keep; fetch'},
{t:'เกรง'	,e:'[is] afraid; fearful; inspired with awe; respectful of; fearful; filled with reverence'},
{t:'เกลา'	,e:'to form into a rough shape; to trim; to clip (e.g. beard, bush)'},
{t:'เกล้า'	,e:'head; mind'},
{t:'เกวียน'	,e:'cart; oxcart; wagon [typically] used to transport grain'},
{t:'เก่า'	,e:'[of an object] [is] old; antique; decrepit'},
{t:'เก้า'	,e:'nine; the number or quantity nine'},
{t:'เก้าอี้'	,e:'chair'},
{t:'เกาะ'	,e:'island'},
{t:'เกิด'	,e:'to be born; to birth; to happen'},
{t:'เกิน'	,e:'to exceed; go beyond; overreach; surpass'},
{t:'เกียจคร้าน'	,e:'[is] lazy, indolent, idle, slothful, inert, inactive'},
{t:'เกียรติยศ'	,e:'honor, prestige, fame, renown, reputation, dignity'},
{t:'เกี่ยว'	,e:'[is] entangled with; [is] hugging; [is] embracing'},
{t:'เกี่ยว'	,e:'to hitch; to link; to hook up'},
{t:'เกี่ยว'	,e:'to mow or harvest, reap, cut'},
{t:'เกี่ยว'	,e:'to concern'},
{t:'เกี่ยวข้อง'	,e:'[is] involved; concerned'},
{t:'เกือบ'	,e:'almost; nearly; close to'},
{t:'แก'	,e:'[impolite or colloquial usage] he; him; she; her; they; them; you'},
{t:'แก่'	,e:'[of a person or animal] [is] old; aged'},
{t:'แก้'	,e:'to undo; remedy; mend; repair; cure; correct; counteract; rectify; quench; slake; relieve; edit'},
{t:'แก้ว'	,e:'[general] glass; transparent or translucent object; crystal; mica'},
{t:'แกะ'	,e:'sheep'},
{t:'โกร่ง'	,e:'apothecary\'s mortar'},
{t:'โกรธ'	,e:'[is] mad; angry; pissed off'},
{t:'ใกล้'	,e:'[is] near; close'},
{t:'ไก่'	,e:'chicken'},
{t:'ไกล'	,e:'[is] far; distant'},
{t:'ขณะ'	,e:'instant; moment, a short time; occasion; juncture; hour'},
{t:'ขด'	,e:'[is] coiled; curled up; rolled up; twisted or bent into a coil'},
{t:'ขด'	,e:'coil; ring; circle'},
{t:'ขด'	,e:'to roll into a coil; to coil; to bend; to twist'},
{t:'ขน'	,e:'[of the body, but not the head, of a human] hair'},
{t:'ขนาด'	,e:'dimensions; size; measurement'},
{t:'ขยาย'	,e:'to expand; enlarge; amplify; inflate; magnify'},
{t:'ขวด'	,e:'bottle'},
{t:'ขวาง'	,e:'to obstruct; impede; be in the way of; bar'},
{t:'ขว้าง'	,e:'to throw; to pitch; to toss; to hurl; to cast; to fling'},
{t:'ขอ'	,e:'to ask for; to request; "I\'d like..." — "May/Can I have...?"'},
{t:'ขอรับ'	,e:'[very formal polite particle used by a male]'},
{t:'ข้อ'	,e:'joint; point of intersection; articulation'},
{t:'ของ'	,e:'of; belonging to; that or those of; [a word used with a pronoun to indicate possesion, as in "John\'s truck"]'},
{t:'ขอบ'	,e:'pertaining to thanks'},
{t:'ขัง'	,e:'to confine; coop up; imprison; retain; detain; cage; incarcerate'},
{t:'ขัด'	,e:'to polish; scrub; rub; abrade; burnish'},
{t:'ขัด'	,e:'to go against; to stop; to hinder; to oppose; to obstruct; to block'},
{t:'ขัด'	,e:'to latch or fasten'},
{t:'ขัน'	,e:'a bowl or basin used for dipping water'},
{t:'ขัน'	,e:'twist; turn'},
{t:'ขัน'	,e:'active; energetic; vigorous; enthusiastic'},
{t:'ขับ'	,e:'to drive; operate; chauffer'},
{t:'ขา'	,e:'[of a human, chair, tripod, etc.] leg; lower extremities'},
{t:'ขา'	,e:'[a journey or trip] trip, time'},
{t:'ขา'	,e:'[of a person] party; side; sort; type'},
{t:'ขา'	,e:'[spoken by a female to indicate an affirmative response] "Yes"'},
{t:'ข้า'	,e:'an attendant; servant; slave; a person under the authority of another'},
{t:'ข้าราชการ'	,e:'government official; civil servant'},
{t:'ข้าศึก'	,e:'enemy'},
{t:'ข้าง'	,e:'towards; in the direction of'},
{t:'ขาด'	,e:'to miss or be absent from an event'},
{t:'ขาด'	,e:'[is] missing a part; incomplete; fragmented'},
{t:'ขาด'	,e:'to tear, rip or become torn or ripped asunder, to separate'},
{t:'ขาด'	,e:'to lack; need'},
{t:'ขาด'	,e:'[is] in short supply; not on hand; lacking; needing'},
{t:'ข้าพเจ้า'	,e:'[a first person pronoun] I, me, my [used when writing or speaking formally]'},
{t:'ข้าม'	,e:'to cross over; pass over; step over'},
{t:'ข้าม'	,e:'across from; opposite'},
{t:'ขาย'	,e:'to sell'},
{t:'ขาว'	,e:'[is] white'},
{t:'ข่าว'	,e:'news; tidings; information received; message'},
{t:'ข้าว'	,e:'rice'},
{t:'ขี่'	,e:'to ride upon, to drive (an animal, bicycle, or motorcycle)'},
{t:'ขีด'	,e:'draw; scratch; write'},
{t:'ขีด'	,e:'100 grams'},
{t:'ขีด'	,e:'a scratch'},
{t:'ขึ้น'	,e:'to ascend; raise; rise; go up'},
{t:'เขต'	,e:'boundary; border; limit; district; territory; zone'},
{t:'เขา'	,e:'[3rd person singular or plural pronoun] he; she; him; her; they; them'},
{t:'เข้า'	,e:'to enter; go in; to penetrate; to insert; to approach'},
{t:'เข้าหู'	,e:'to hear; to have heard'},
{t:'เขียน'	,e:'to write; to draw'},
{t:'เขียว'	,e:'[is] green'},
{t:'แขก'	,e:'visitor; guest; foreigner'},
{t:'แข็ง'	,e:'[is] hard; solid; stiff; rigid; strong; firm; [of a swimmer] strong'},
{t:'แข่ง'	,e:'to compete; to race; to contend with; to strive for; to vie'},
{t:'ไข'	,e:'open; unfold; explain; unlock; tell; expand'},
{t:'ไข'	,e:'to wind (up) or unwind; to turn'},
{t:'ไข'	,e:'animal fat; lard; tallow; [of human bones] marrow'},
{t:'ไข่'	,e:'egg'},
{t:'ไข้'	,e:'fever; a temperature of the body; sickness'},
{t:'คณะ'	,e:'council; group; member; corporation'},
{t:'คณะ'	,e:'faculty of a college or university'},
{t:'คดี'	,e:'lawsuit; legal action; case'},
{t:'คน'	,e:'person; guy; people; man; human being'},
{t:'ค้น'	,e:'to search'},
{t:'ครบ'	,e:'[is] complete; whole; every; entire; due'},
{t:'ครอง'	,e:'to rule; to govern; to regulate by authority; to exercise or assert authority; to direct'},
{t:'ครอง'	,e:'to occupy; to possess and enjoy the use of'},
{t:'ครอบครัว'	,e:'family'},
{t:'ครั้ง'	,e:'[frequency] time; occasion; instance; event; occurrence'},
{t:'ครั้น'	,e:'when (something occurs); if (something happened)'},
{t:'ครับ'	,e:'[word added by a male speaker to the end of every sentence to convey politeness or] "yes"; "that\'s right"; "I see."'},
{t:'คราว'	,e:'occasion; time; episode'},
{t:'ครึ่ง'	,e:'half; midway; mid; ½'},
{t:'ครู'	,e:'teacher; instructor'},
{t:'คลอง'	,e:'[of water] a canal'},
{t:'คลาย'	,e:'to diminish; to unwind; to relax; to slacken; to abate; to lessen; to untwist; to unfurl; to decrease'},
{t:'คลุม'	,e:'[is] covered (over); hidden; unclear; enveloped; blanketed (with)'},
{t:'ควร'	,e:'[auxiliary verb indicating] should; ought to; must'},
{t:'ความ'	,e:'[a prefix which converts an adjective or verb into a noun]'},
{t:'ควาย'	,e:'[general] water buffalo'},
{t:'คอ'	,e:'neck; throat'},
{t:'คอย'	,e:'to wait or wait for'},
{t:'ค่อย'	,e:'gently; softly; little by little; gradually; cautiously'},
{t:'คะ'	,e:'[word added by a female speaker to the end of every question to convey politeness]'},
{t:'ค่ะ'	,e:'[word added by a female speaker to the end of every statement to convey politeness]'},
{t:'คับ'	,e:'[is] tight; confined; crowded; closely packed; tight-fitting; close-fitting'},
{t:'ค่า'	,e:'value; price; charge; cost; expense'},
{t:'ค้า'	,e:'to trade; to do business; to do commerce; to barter; to buy and sell; to vend; to traffic in'},
{t:'คำ'	,e:'word; term; discourse'},
{t:'ค่ำ'	,e:'evening; dusk; sunset time'},
{t:'คิด'	,e:'to think; consider; imagine; to compute; to count; to wonder'},
{t:'คืน'	,e:'night'},
{t:'คือ'	,e:'[copula] to be; (conjunction used for equivalence definitions)'},
{t:'คุณ'	,e:'[singular and plural] you; your'},
{t:'คู'	,e:'ditch; moat'},
{t:'คูณ'	,e:'to multiply; mathematical multiplication; "times"'},
{t:'เคย'	,e:'(have you) ever; (as) before; did in the past; used to...'},
{t:'เคย'	,e:'[auxiliary verb] used to...; did once...'},
{t:'เครื่อง'	,e:'machine; apparatus; engine; mechanical device'},
{t:'เคลื่อน'	,e:'to move to another place; to move or relocate in a supervised or organized fashion'},
{t:'เคียง'	,e:'[is] adjoining; connected; beside; near; close together'},
{t:'เคือง'	,e:'[is] angry; peeved; indignant; wrathful; irate; offended; annoyed'},
{t:'โคม'	,e:'lamp; lantern'},
{t:'ใคร'	,e:'anyone; anybody; someone; somebody; whoever'},
{t:'ใคร่'	,e:'to desire; wish; prefer'},
{t:'งอก'	,e:'to sprout; bud; grow; shoot off'},
{t:'งาน'	,e:'work; job; duty; business; function'},
{t:'งาม'	,e:'[is] beautiful; pretty; attractive; gorgeous; fine; complete'},
{t:'ง่าย'	,e:'[is] easy; not difficult; simple'},
{t:'งู'	,e:'snake'},
{t:'เงิน'	,e:'money; finance; silver'},
{t:'เงียบ'	,e:'[is] quiet; peaceful; silent'},
{t:'โง่'	,e:'[is] stupid; silly; dumb; foolish; vain'},
{t:'จง'	,e:'[auxiliary verb used to indicate a command or order] should; ought to'},
{t:'จด'	,e:'to take note; to jot down'},
{t:'จดหมาย'	,e:'postal letter; mail; a letter'},
{t:'จน'	,e:'[most commonly used term] [is] poor; penniless; having nothing; impoverished'},
{t:'จบ'	,e:'to end; to finish'},
{t:'จบ'	,e:'end; finale'},
{t:'จม'	,e:'to sink; drown; submerge'},
{t:'จริง'	,e:'truthful; truthfully; really?; true; real; serious; no-nonsense; well; so'},
{t:'จริต'	,e:'behavior; conduct; act (outward act)'},
{t:'จะ'	,e:'[auxiliary verb indicating future tense—must be used with another verb] will; shall'},
{t:'จัก'	,e:'to cleave, split, or serrate'},
{t:'จัก'	,e:'[is] serrated; notched'},
{t:'จักร'	,e:'circle; wheel; disk; discus; cycle'},
{t:'จัง'	,e:'greatly; extremely; truly; fully; quite; most; very much so'},
{t:'จังหวัด'	,e:'province, of which Thailand has 76'},
{t:'จัด'	,e:'to adjust; arrange; fix'},
{t:'จัด'	,e:'strong; intense; excessive; severe [especially when speaking of the weather]'},
{t:'จันทร์'	,e:'the Moon'},
{t:'จับ'	,e:'to arrest; catch; get a hold of; touch; capture; seize'},
{t:'จาก'	,e:'from'},
{t:'จ้าง'	,e:'to hire; engage; employ'},
{t:'จ่าย'	,e:'to spend; purchase; shop; disburse money; pay'},
{t:'จำ'	,e:'to remember; to recall; to memorize; to retain; to recognize; to recollect'},
{t:'จำเป็น'	,e:'[is] necessary; essential; required; to need to (do something)'},
{t:'จำพวก'	,e:'species; type; group'},
{t:'จำนวน'	,e:'amount; number; quantity (of countable nouns)'},
{t:'จิต'	,e:'the mind; mentality'},
{t:'จิต'	,e:'of the mind; mental'},
{t:'จีน'	,e:'China; Chinese'},
{t:'จึง'	,e:'thus; therefore; so'},
{t:'จูบ'	,e:'to kiss'},
{t:'เจ็ด'	,e:'seven; the number or quantity seven'},
{t:'เจ็บ'	,e:'[is] sore; hurt; injured; in pain; in emotional pain'},
{t:'เจริญ'	,e:'to progress; grow; prosper; thrive; expand'},
{t:'เจริญ'	,e:'[is] prosperous'},
{t:'เจ้า'	,e:'prince; princess; ruler; esteemed person; lord; master; holy being'},
{t:'เจาะ'	,e:'to puncture; to bore; to pierce; to punch a hole; to perforate'},
{t:'แจง'	,e:'an explanation'},
{t:'แจ้ง'	,e:'to notify; advise; inform; make apparent'},
{t:'แจ่ม'	,e:'clear; bright; distinct; cheerful'},
{t:'โจทย์'	,e:'accusation; objection'},
{t:'ใจ'	,e:'heart; spirit; spiritual center or core; soul; inner being; mind'},
{t:'ฉบับ'	,e:'transcript; document; copy'},
{t:'ฉบับ'	,e:'edition, copy, issue of a magazine or newspaper; [formal term officially endorsed by the Royal Institute] version (of software)'},
{t:'ฉลาด'	,e:'[is] smart; intelligent; clever'},
{t:'ฉะนั้น'	,e:'consequently; thus'},
{t:'ฉะนี้'	,e:'consequently; so; thus'},
{t:'ฉัน'	,e:'[used by females in an informal setting—also used by males with intimate friends or lovers] I, me, my'},
{t:'เฉพาะ'	,e:'[is] specific; particular; limited; provisional'},
{t:'ไฉน'	,e:'why; wherefore'},
{t:'ชน'	,e:'to collide; to crash; bump; bump together'},
{t:'ชน'	,e:'(singular) person; (plural) people'},
{t:'ชนวน'	,e:'fuse; primer; harbinger'},
{t:'ชนะ'	,e:'to conquer; defeat; beat; win'},
{t:'ชนิด'	,e:'class; sort; type; variety; category; group; kind; species; in the style of...'},
{t:'ชม'	,e:'to admire; compliment; praise; commend; extol; flatter; pay tribute to; salute; speak highly of'},
{t:'ชลประทาน'	,e:'irrigation'},
{t:'ชวน'	,e:'to persuade; to induce; to urge; to invite; to ask; to influence; to prevail upon; to agree'},
{t:'ช่วย'	,e:'to help; to aid; to assist; to contribute; to please'},
{t:'ช่อง'	,e:'passage; aperature; gap; hole; lane; opening; [euphonious word for บ้าน ]'},
{t:'ชอบ'	,e:'to like; to prefer; to be pleased with; to be fond of; to admire; to be satisfied with; to be right for'},
{t:'ชัก'	,e:'to pull at; to discount; draw; take away; withdraw; to pull upon'},
{t:'ชัด'	,e:'[is] sharp; clear; focused; concise'},
{t:'ชั้น'	,e:'class; rank; grade'},
{t:'ชั่ว'	,e:'[is] bad; evil; wicked'},
{t:'ชั่วโมง'	,e:'[in time; of time] an hour (when used as a quantity)'},
{t:'ชัวร์'	,e:'[Thai transcription of the foreign loanword] sure; surely; certainly'},
{t:'ชา'	,e:'[general] tea'},
{t:'ช้า'	,e:'[is] slow'},
{t:'ช่าง'	,e:'engineer; artisan; mechanic; craftsman; specialist; repairman; barber'},
{t:'ช้าง'	,e:'elephant; pachyderm; Elephas maximus'},
{t:'ชาติ'	,e:'national; of a nation; race; of a country'},
{t:'ชาย'	,e:'male'},
{t:'ชายหาด'	,e:'beach'},
{t:'ชาว'	,e:'folk; people; people of'},
{t:'ชำนาญ'	,e:'[is] experienced; skilled; expert; adroit'},
{t:'ชิง'	,e:'to snatch away, to wrest away from, to contest or compete for, to vie'},
{t:'ชี้'	,e:'to point (out); to indicate a location'},
{t:'ชีพ'	,e:'life; existence; living'},
{t:'ชีวิต'	,e:'life'},
{t:'ชื่อ'	,e:'name; the first name of a person; the name of a place or thing; appellation; designation; a Christian name; denomination'},
{t:'เช่น'	,e:'example; sample; specimen'},
{t:'เช่น'	,e:'such as; for example; for instance; like; e.g.'},
{t:'เช่น'	,e:'similar to; same as'},
{t:'เช่น'	,e:'as'},
{t:'เช้า'	,e:'morning, specifically, hours between 6:00 a.m. and 11:00 a.m. or typically 9:00 a.m.'},
{t:'เชื่อ'	,e:'to believe; to trust; to have faith in; to rely on'},
{t:'เชื้อ'	,e:'bacteria; microbe; yeast; germ'},
{t:'เชื้อ'	,e:'flammable fuel'},
{t:'โชค'	,e:'luck'},
{t:'ใช่'	,e:'yes; I agree; correct; right; indeed; that\'s so'},
{t:'ใช้'	,e:'to use, to employ or exploit an object; to utilize; to resort to; to implement'},
{t:'ซ่อน'	,e:'to conceal or hide an item or oneself'},
{t:'ซ้าย'	,e:'left direction (opposite of right)'},
{t:'ซ้ำ'	,e:'[is] repeated; recurrent'},
{t:'ซ้ำ'	,e:'to repeat; to recur; to reiterate'},
{t:'ซิ'	,e:'[a particle which conveys urgency, adding an imperative quality] (this is the way it is or must be)'},
{t:'ซีก'	,e:'section; piece; part; portion [as in the English prefix] hemi-'},
{t:'ซึ่ง'	,e:'[the relative pronouns] that; which'},
{t:'ซึ่ง'	,e:'[the relative pronouns] who; whose; whom; of which'},
{t:'ซื่อ'	,e:'[is] faithful; loyal; honest'},
{t:'ซื้อ'	,e:'to buy or purchase'},
{t:'ญาติ'	,e:'relative; kin; relations; cousins'},
{t:'ญี่ปุ่น'	,e:'Japan'},
{t:'ดง'	,e:'jungle; thick grove'},
{t:'ดวง'	,e:'orb; spherical object; astrological sign'},
{t:'ด้วย'	,e:'together; along with; also; too; as well; likewise; in addition to doing some other thing (as another action performed by the same subject)'},
{t:'ดอก'	,e:'flower'},
{t:'ดัง'	,e:'[is] loud; noisy'},
{t:'ดับ'	,e:'to eliminate, to stop; to die or pass away'},
{t:'ดับ'	,e:'to extinguish; put out; vanquish; dead'},
{t:'ด้าน'	,e:'side; face; direction; quarter; sector; aspect; surface; field; viewpoint'},
{t:'ด้าน'	,e:'[is] callous; hard; hard-hearted; hardened; shameless'},
{t:'ดาว'	,e:'star; a non-planetary celestial body; spot'},
{t:'ดำ'	,e:'[is] black; dark; dusky'},
{t:'ดำเนิน'	,e:'to implement, to go forward with a plan, to conduct or proceed, to operate, carry out'},
{t:'ดำริ'	,e:'[Royal use only] to think'},
{t:'ดิน'	,e:'dirt; earth; soil; ground; land; kingdom; realm'},
{t:'ดี'	,e:'[is] good; well; fine; nice'},
{t:'ดื่ม'	,e:'to drink; <subject> drinks'},
{t:'ดุจ'	,e:'similar to, as if, as though'},
{t:'ดู'	,e:'to look at; examine; or inspect; to watch (for example, a film)'},
{t:'เด็ก'	,e:'child'},
{t:'เดิน'	,e:'to walk; <subject> walks'},
{t:'เดิม'	,e:'the origin; beginning; start'},
{t:'เดียว'	,e:'[is] single; alone'},
{t:'เดี่ยว'	,e:'[is] single; alone; sole'},
{t:'เดี๋ยว'	,e:'soon; shortly; momentarily'},
{t:'เดี๋ยวนี้'	,e:'now; "Right now!"; "Pronto!"'},
{t:'เดือด'	,e:'to boil by heat; to be iritated; to be provoked; to boil over; to be furious; to be in a rage'},
{t:'เดือน'	,e:'month'},
{t:'แดง'	,e:'[is] red'},
{t:'แดด'	,e:'sunlight; sunshine; sun; strong sunlight; rays of the sun'},
{t:'แดน'	,e:'border; land boundary; area; region'},
{t:'โดย'	,e:'by; via; the method; route; way or mode of attainment'},
{t:'ใด'	,e:'[is] any'},
{t:'ได้'	,e:'can; to be able; is able; am able; may; might [auxiliary of potential, denoting possbility, ability, or permission]'},
{t:'ตก'	,e:'to fall; to drop or pour down; to fail'},
{t:'ตน'	,e:'self; person; man; oneself'},
{t:'ต้น'	,e:'[a prefix used for plant or tree names] plant; stalk; trunk; tree'},
{t:'ตรง'	,e:'[is] straight; direct; exactly; upright; vertical'},
{t:'ตรวจ'	,e:'to check; test; examination; inspection'},
{t:'ตระกูล'	,e:'family; lineage; pedigree; lineage'},
{t:'ตรัส'	,e:'[as a king or royalty] to say; remark; speak; declare; pronounce'},
{t:'ตรา'	,e:'brand name; brand; seal; stamp; mark; hallmark; device; decoration; badge'},
{t:'ตลอด'	,e:'during; all during; throughout; through; in (e.g., in over 20 years)'},
{t:'ตลาด'	,e:'market'},
{t:'ต่อ'	,e:'against; towards; to; further; on'},
{t:'ต่อ'	,e:'to battle'},
{t:'ต่อ'	,e:'[of contracts, ropes, etc.] to extend, to lengthen; [of phone calls] to connect; [of words] to join, to link; [of knowledge] to receive or inherit'},
{t:'ต่อ'	,e:'telephone extension'},
{t:'ต่อ'	,e:'to connect'},
{t:'ต่อ'	,e:'connector'},
{t:'ต่อ'	,e:'[specifiying temporal sequence] next; afterward; later on; continued'},
{t:'ต่อ'	,e:'to bargain or haggle; to negotiate'},
{t:'ต้อง'	,e:'[auxiliary verb] has to...; must...; is required to...; is duty-bound to...'},
{t:'ตอน'	,e:'a period of time; during...; an interval; when...'},
{t:'ต้อน'	,e:'to herd; or corner; gather together'},
{t:'ตอบ'	,e:'to answer; reply; respond'},
{t:'ตะเกียง'	,e:'lamp; oil lamp; lantern'},
{t:'ตะวัน'	,e:'the Sun'},
{t:'ตั้ง'	,e:'to decree; lay down; formulate (laws, rules, regulations, questions)'},
{t:'ตัด'	,e:'to cut; mow; trim; sever; hew; make (a suit); build (a road)'},
{t:'ตัดสิน'	,e:'to decide; judge; referee'},
{t:'ตัว'	,e:'[of a person] self; himself; herself; yourself; themselves; [things] itself'},
{t:'ตัวอย่าง'	,e:'example; sample'},
{t:'ตา'	,e:'eye'},
{t:'ต้าน'	,e:'to resist; oppose; stop; withstand; impede; hinder; [the prefix] anti-'},
{t:'ตาม'	,e:'to follow; along; around'},
{t:'ตาม'	,e:'according to'},
{t:'ตาม'	,e:'to fetch (someone); to send for (someone)'},
{t:'ตาย'	,e:'[general] to die; be dead; perish; decease; expire; terminate; pass away; (car) stop (working)'},
{t:'ตำ'	,e:'beat; pound an object; pulverize'},
{t:'ตำ'	,e:'to pierce; puncture; prick'},
{t:'ต่ำ'	,e:'[is] low; short; depressed; base'},
{t:'ตำบล'	,e:'sub-district, a subdivision of the อำเภอ'},
{t:'ตำแหน่ง'	,e:'position; post; rank'},
{t:'ติด'	,e:'[of a person] to become (figuratively) fixated (on something); to think about (something) to an extreme and excessive degree; to be (figuratively) absorbed; to be obsessed (with someone or something); to be crazy or mad about; to be fascinated by'},
{t:'ตี'	,e:'to beat; hit; strike; or whip'},
{t:'ตึก'	,e:'building; brickwork; a brick structure'},
{t:'ตุลาคม'	,e:'October'},
{t:'ตู้'	,e:'storage cabinet; post office box; cupboard; locker for luggage; (gym clothing) locker'},
{t:'เต็ม'	,e:'[is] complete; full'},
{t:'เตรียม'	,e:'to prepare; to be ready; to ready'},
{t:'เตียง'	,e:'bed'},
{t:'เตือน'	,e:'to caution; warn; remind'},
{t:'แต่'	,e:'but; even; however; rather'},
{t:'แตก'	,e:'to break; burst; shatter; smash; break in pieces; break out; blossom'},
{t:'แต่ง'	,e:'to adorn; decorate; beautify'},
{t:'โต'	,e:'[is] big; large; grown'},
{t:'โต๊ะ'	,e:'table'},
{t:'ใต้'	,e:'South; Southern'},
{t:'ไต่'	,e:'to climb; to scale (a mountain); to move up slowly and carefully'},
{t:'ถนน'	,e:'road; boulevard; avenue; street'},
{t:'ถวาย'	,e:'to give; offer; present'},
{t:'ถอย'	,e:'to withdraw; move back; retreat'},
{t:'ถ้อย'	,e:'words; wording; speech; utterance; diction; verbal expression; statement; terms'},
{t:'ถั่ว'	,e:'a bean or pea plant; a bean'},
{t:'ถ้า'	,e:'[indicating a condition] if'},
{t:'ถาม'	,e:'to ask (a question); to inquire; to quiz; to interrogate'},
{t:'ถูก'	,e:'[is] true; correct; right; conforming'},
{t:'ถูก'	,e:'[a verb particle reflecting passive voice]'},
{t:'เถิด'	,e:'[a formal word placed after a verb or a sentence to mark or indicate an exhortation, a command or an entreaty] let\'s; let us; let\'s go for it; let\'s do it'},
{t:'เถียง'	,e:'to contradict; to argue; to dispute; to talk back'},
{t:'แถว'	,e:'[of objects] a row; column; file; line; bank; queue'},
{t:'ไถ'	,e:'to plow; thrust; push; to clip hair very short'},
{t:'ทดลอง'	,e:'to experiment; test'},
{t:'ทน'	,e:'to bear; stand; put up with; tolerate; endure; last'},
{t:'ทรง'	,e:'form; figure; style'},
{t:'ทรง'	,e:'[royal use only] [prefix which transforms common verbs (and sometimes nouns) into the verbs (and nouns) for royal language showing actions of mounting (a horse) or holding (an object), etc. The meanings will depend on such ensuing verbs.]'},
{t:'ทรง'	,e:'hair style; hairdo'},
{t:'ทรัพย์'	,e:'asset; wealth; possessions; riches'},
{t:'ทราบ'	,e:'[polite] to know a fact or piece of information'},
{t:'ทวี'	,e:'to multiply; increase; add; double'},
{t:'ทวีป'	,e:'continent'},
{t:'ทหาร'	,e:'military; army; soldier'},
{t:'ท่อ'	,e:'duct; pipe; hose'},
{t:'ท่อ'	,e:'ditch'},
{t:'ทอง'	,e:'gold; Au'},
{t:'ทองคำ'	,e:'gold; gold nugget'},
{t:'ท้อง'	,e:'belly; abdomen; stomach'},
{t:'ทอด'	,e:'[is] deep-fried'},
{t:'ทะเล'	,e:'sea'},
{t:'ทั้ง'	,e:'all; entire; whole; wholly; both (...and); while'},
{t:'ทั้งปวง'	,e:'all; in total; completely; of every kind; as a whole'},
{t:'ทั้งหลาย'	,e:'all; many; several'},
{t:'ทัน'	,e:'to overtake; catch up with; be on time; be abreast of'},
{t:'ทับ'	,e:'to place on top of or overlay; superimpose; run over'},
{t:'ทัพ'	,e:'army; fighting forces; force; troops; armed forces'},
{t:'ทั่ว'	,e:'all; entire; complete; whole; throughout'},
{t:'ทา'	,e:'to apply; paint; put on lotion or makeup'},
{t:'ทาง'	,e:'direction; way; course; the way'},
{t:'ทาน'	,e:'[formal, yet abbreviated] to eat'},
{t:'ท่าน'	,e:'[a respectful 2nd or 3rd person singular pronoun] you; he; she; him; her'},
{t:'ทาบ'	,e:'to brace or splice with a long piece alongside'},
{t:'ทาย'	,e:'to foretell; prophesy; predict; guess'},
{t:'ทาย'	,e:'[of a problem] to solve; to answer'},
{t:'ท้าย'	,e:'at the back; at the end'},
{t:'ท้าย'	,e:'stern; back; rear end'},
{t:'ท้าว'	,e:'[title for a king or god]'},
{t:'ทำ'	,e:'to do or perform an action; to cause or effect a result'},
{t:'ทำไม'	,e:'why'},
{t:'ทำลาย'	,e:'to damage; harm; do harm; destroy; ruin; crush'},
{t:'ทิ้ง'	,e:'to abandon; discard; throw away; to leave (an object) behind'},
{t:'ทิศ'	,e:'[a named] direction or point of the compass (such as east, west, north, and south, or right and left); a quarter section of the horizon'},
{t:'ที'	,e:'turn; outing; chance; opportunity; instance; times; occasion'},
{t:'ทีเดียว'	,e:'quite; very'},
{t:'ที่'	,e:'at; on the site of; within; amidst; in the location of'},
{t:'ทุก'	,e:'every; each'},
{t:'ทุกข์'	,e:'suffering; sorrow; distress; adversity; trouble; anxiety; first of the Four Noble Truths'},
{t:'ทุ่ง'	,e:'field; plain; pasture'},
{t:'ทูต'	,e:'ambassador; diplomat; emissary; envoy; attaché'},
{t:'ทูน'	,e:'to place in an elevated position; to respect; to revere; to worship; to esteem'},
{t:'เท'	,e:'to take away in large numbers; to haul off; to pour'},
{t:'เท็จ'	,e:'[is] false; untrue; dishonest; deceptive; spurious'},
{t:'เทวดา'	,e:'a male angel'},
{t:'เท่า'	,e:'[is] equal; equivalent; even; as much as'},
{t:'เท่าไร'	,e:'...how much?... how many?; to that extent'},
{t:'เท้า'	,e:'foot; feet; paw'},
{t:'เที่ยง'	,e:'12:00 h; 12 p.m.; noon'},
{t:'เทียบ'	,e:'to compare; to place alongside; to escort'},
{t:'เทียม'	,e:'[is] artificial; false; imitation'},
{t:'เที่ยว'	,e:'a trip; vacation; holiday; pleasure tour'},
{t:'แท้'	,e:'[is] genuine; real; true'},
{t:'แทน'	,e:'to subsitute; represent; replace'},
{t:'แทน'	,e:'instead'},
{t:'แทน'	,e:'substitute; replacement; deputized; representative'},
{t:'แทบ'	,e:'nearly; almost'},
{t:'โทษ'	,e:'punishment; penalty; penance; guilt; blame; offence; crime; penalty; ill-effect; harm; danger; fault; defect; sinfulness; misdeed'},
{t:'ไทย'	,e:'Thai; of or pertaining to Thailand'},
{t:'ธง'	,e:'flag'},
{t:'ธรรม'	,e:'dharma; religious teaching; religious duty'},
{t:'ธรรม'	,e:'virtue; morality; precept; scruples; rightneousness; principles; doctrine'},
{t:'ธรรม'	,e:'morals and ethics; the good and decent principles of life'},
{t:'ธรรม'	,e:'truth; enlightenment'},
{t:'ธรรม'	,e:'justice; fairness'},
{t:'ธรรม'	,e:'rule; law; regulation'},
{t:'ธรรมดา'	,e:'[is] usual; ordinary; normal; average; plain; regular; natural; common'},
{t:'ธรรมเนียม'	,e:'custom; customs; tradition; traditional usage'},
{t:'ธันวาคม'	,e:'December'},
{t:'ธาตุ'	,e:'one of the four ancient elements: earth, water, air, or fire'},
{t:'ธุระ'	,e:'business; personal business; errands'},
{t:'เธอ'	,e:'[used in intimate or informal settings] you [the 2nd person singular pronoun]'},
{t:'นก'	,e:'bird'},
{t:'นคร'	,e:'city; town; municipality'},
{t:'นม'	,e:'[general] milk'},
{t:'นอก'	,e:'[is] outside of; external to; foreign; alien'},
{t:'นอกจาก'	,e:'except; unless; with the exception of...; other than...; besides; not only'},
{t:'น้อง'	,e:'younger sibling; younger friend; younger colleague'},
{t:'นอน'	,e:'to sleep; lie down'},
{t:'น้อย'	,e:'[is] little; small; minor; tiny; less; few; slight; a little bit; a small amount'},
{t:'นัก'	,e:'[word used before a verb or noun to describe a profession] person who; enthusiast; devotee; expert'},
{t:'นักปราชญ์'	,e:'philosopher'},
{t:'นักเรียน'	,e:'student; pupil (thru high school); schoolchildren'},
{t:'นั่ง'	,e:'to sit or be sitting'},
{t:'นั่น'	,e:'there (at a medium distance from here); those; that'},
{t:'นั้น'	,e:'that one; object at a medium distance; those'},
{t:'นับ'	,e:'to count'},
{t:'นับถือ'	,e:'to respect; esteem; revere; reckon; hold in high regard; believe in; profess'},
{t:'นา'	,e:'rice farm; rice paddy; grain field'},
{t:'น่า'	,e:'[a prefix to a verb or adjective indicating a likely or probable state, as in the English suffix] "-able"'},
{t:'น่า'	,e:'[a prefix to a verb or adjective to indicate a persistent state or greater intensity of description] extremely; very; intensely; entrenched; really'},
{t:'นาง'	,e:'woman'},
{t:'นาน'	,e:'long time'},
{t:'นาม'	,e:'name; designation; appellation'},
{t:'นาฬิกา'	,e:'timepiece; clock; wristwatch; watch'},
{t:'นำ'	,e:'to lead or precede'},
{t:'น้ำ'	,e:'water; fluid; liquid'},
{t:'น้ำแข็ง'	,e:'ice'},
{t:'น้ำมัน'	,e:'oil; gasoline; fuel'},
{t:'นิ่ง'	,e:'[is] still; immobile; silent; motionless; quiet'},
{t:'นิด'	,e:'[is] tiny; very small; microscopic'},
{t:'นิทาน'	,e:'fable; story; yarn; tale; folklore; fairytale'},
{t:'นิยม'	,e:'[is] popular'},
{t:'นิ้ว'	,e:'finger; toe; digit'},
{t:'นี่'	,e:'this'},
{t:'นี้'	,e:'this; these'},
{t:'นึก'	,e:'to suppose, think or conjecture; to feel, ponder, harbor a feeling or doubt,'},
{t:'นุ่ง'	,e:'to dress; don; put on; wear clothing; to get dressed; attire; clothe; garb; robe; slip on or into'},
{t:'เนื้อ'	,e:'beef; flesh; tissue meat of any animal [especially] meat of the cow'},
{t:'เนื่อง'	,e:'[is] due to; related or connected to; a result of'},
{t:'แน่'	,e:'[is] sure; certain; truthful; firm; stable; without doubt; exact'},
{t:'แน่น'	,e:'[is] crowded; busy (restaurant, etc); tightly packed'},
{t:'แน่น'	,e:'[is] tight; firm; secure'},
{t:'แนะนำ'	,e:'[of a person] to introduce'},
{t:'แนะนำ'	,e:'[of an idea] to introduce; suggest; advise; direct; guide; recommend'},
{t:'โน้น'	,e:'that one over there; a distant object'},
{t:'ใน'	,e:'in; inside; within; amidst; into; on; at a particular time'},
{t:'บก'	,e:'land; dry land; terra firma; high ground'},
{t:'บท'	,e:'chapter of a book; lesson of a schoolbook; article in a magazine; verse; stanza'},
{t:'บทบรรณาธิการ'	,e:'editorial'},
{t:'บน'	,e:'over; above; on; upon; in'},
{t:'บรรดา'	,e:'all; in general; those'},
{t:'บริบูรณ์'	,e:'[is] perfect, complete, full, flawless'},
{t:'บริษัท'	,e:'company; firm; corporation; congregration; audience; meeting; assembly'},
{t:'บริสุทธิ์'	,e:'[is] innocent; pure; uncontaminated; virgin; fine'},
{t:'บอก'	,e:'to say; tell; inform; mention; state; relate; let (someone) know'},
{t:'บ่อย'	,e:'often'},
{t:'บัง'	,e:'to hide; to conceal; to block the view; to screen, share or shield; to obscure'},
{t:'บังคับ'	,e:'to force; compel; command; control; coerce; enforce; compulsory; mandatory'},
{t:'บังเกิด'	,e:'to beget; produce; engender; conceive; pop up'},
{t:'บัญชา'	,e:'to command; direct'},
{t:'บัญญัติ'	,e:'legal act; law; decree; ordance; regulation'},
{t:'บาง'	,e:'[is] scarce; limited; few; rare; thin'},
{t:'บาง'	,e:'[is] thin; weak; light; fine'},
{t:'บางที'	,e:'maybe; sometimes; perhaps'},
{t:'บ้าง'	,e:'some; any; partially'},
{t:'บาท'	,e:'Thai currency: Baht (TH฿)'},
{t:'บาน'	,e:'to bloom; open; blossom; unfold'},
{t:'บ้าน'	,e:'house; home; place (or one\'s place); village'},
{t:'บ่าย'	,e:'afternoon hours between 1:00 p.m. and 4:00 p.m.'},
{t:'บำรุง'	,e:'to care for; maintain; nurture; support'},
{t:'บิดา'	,e:'father'},
{t:'บุคคล'	,e:'person; individual; man; commoner'},
{t:'บุญ'	,e:'good deeds; merit'},
{t:'บุญ'	,e:'holy; virtuous; pure; sacred'},
{t:'บุตร'	,e:'child, offspring, son or daughter'},
{t:'บุตรี'	,e:'daughter'},
{t:'บุรุษ'	,e:'man; male; gentleman; person; people; mankind; humans'},
{t:'บุหรี่'	,e:'cigarette'},
{t:'เบอร์'	,e:'number; digit'},
{t:'เบี้ย'	,e:'a small amount of money'},
{t:'เบี้ย'	,e:'a counter used in gambling'},
{t:'เบื้อง'	,e:'[prefix for a (spatial) direction]'},
{t:'แบ่ง'	,e:'to share; divide into parts; apportion'},
{t:'แบน'	,e:'[is] flat'},
{t:'แบบ'	,e:'plan; kind; design; pattern; style; model; type; [formal term officially endorsed by the Royal Institute] version (of software)'},
{t:'โบราณ'	,e:'[is] ancient'},
{t:'ใบ'	,e:'paper; sheet; card; ticket; document; blade'},
{t:'ปกครอง'	,e:'to rule; administer; govern'},
{t:'ปฏิบัติ'	,e:'to execute; perform; do; act; behave, practice'},
{t:'ปรกติ'	,e:'[is] normal; usual; routine'},
{t:'ประกอบ'	,e:'to combine; to put together; to build; to assemble; to make; to erect'},
{t:'ประการ'	,e:'type; kind; sort; species; variety; method; item'},
{t:'ประกาศ'	,e:'to announce; to proclaim; to declare; to notify; to publish'},
{t:'ประกาศ'	,e:'bill'},
{t:'ประจำ'	,e:'[is] assigned; permanently placed; constant; fixed'},
{t:'ประชุม'	,e:'to assemble; have a meeting'},
{t:'ประตู'	,e:'door; gate; doorway; entrance'},
{t:'ประเทศ'	,e:'nation; country'},
{t:'ประพฤติ'	,e:'to behave; to conduct oneself; to act; to perform or do'},
{t:'ประพฤติ'	,e:'manner; conduct; deportment; behavior'},
{t:'ประมาณ'	,e:'approximately; about; roughly'},
{t:'ประโยชน์'	,e:'benefit; use; usefulness'},
{t:'ประโยชน์'	,e:'useful; beneficial'},
{t:'ประสงค์'	,e:'to wish or desire'},
{t:'ประเสริฐ'	,e:'[is] excellent; glorious; sublime; superb; outstanding'},
{t:'ประหลาด'	,e:'[is] strange; odd; weird; peculiar; wonderful; marvelous; queer; unusual; surprising'},
{t:'ปรากฏ'	,e:'to appear; to seem; to reveal'},
{t:'ปราบปราม'	,e:'to repress; quell; quash; subjugate'},
{t:'ปรารถนา'	,e:'to wish for; to desire'},
{t:'ปราศจาก'	,e:'[is] without; separate from; [is] rid of; [is] free from'},
{t:'ปล่อย'	,e:'to let go; relinquish; discharge; emit; abandon; release; ease'},
{t:'ปลา'	,e:'fish'},
{t:'ปลาบ'	,e:'[is] thrilling; flashing; shining'},
{t:'ปลูก'	,e:'to cultivate; to plant; build; to grow a plant'},
{t:'ปวง'	,e:'in general; as a group; taken together'},
{t:'ป้องกัน'	,e:'to defend; protect against; prevent; prevent against; bar'},
{t:'ปัญญา'	,e:'[Buddhism] intelligence; wisdom; sharpness; wit'},
{t:'ปัญหา'	,e:'problem; trouble; difficulty'},
{t:'ปั้น'	,e:'to mold; form; fabricate'},
{t:'ป่า'	,e:'forest; woods; jungle; wild'},
{t:'ปาก'	,e:'mouth or any part in the mouth or lip areas; lips; orifice; (animal\'s) muzzle'},
{t:'ปิด'	,e:'to close; turn off; to shut'},
{t:'ปี'	,e:'year; annum; annual'},
{t:'เป็ด'	,e:'duck'},
{t:'เป็น'	,e:'to be; <subject> is'},
{t:'เปรียบ'	,e:'to compare; to contrast'},
{t:'เปล่า'	,e:'[is] void; empty; naked; nothing'},
{t:'เปลี่ยน'	,e:'to change; replace; to convert; to alter; swap; substitute; to transplant'},
{t:'เปลือก'	,e:'bark; rind; husk; shell; skin; peel'},
{t:'เปลือง'	,e:'to use up; consume; waste'},
{t:'เปิด'	,e:'to open; to turn on; engage'},
{t:'แปด'	,e:'eight; the number or quantity eight'},
{t:'แปลก'	,e:'[is] strange; unusual; queer; weird; peculiar; odd; curious'},
{t:'แปลง'	,e:'plot of land; flower bed; field'},
{t:'แปลง'	,e:'to convert; modify; adapt'},
{t:'โปรด'	,e:'[a formal word of request] "please"'},
{t:'ไป'	,e:'to go; <subject> goes'},
{t:'ไปรษณีย์'	,e:'post; mail; post office; postal system'},
{t:'ผม'	,e:'[used by male speakers] I; me; my'},
{t:'ผม'	,e:'hair [of the head]'},
{t:'ผล'	,e:'fruit'},
{t:'ผสม'	,e:'to combine; mix'},
{t:'ผ้า'	,e:'cloth; material; fabric'},
{t:'ผ่าน'	,e:'to cross; pass; pass by; pass through'},
{t:'ผิด'	,e:'[is] incorrect; wrong; mistaken; false; faulty; guilty'},
{t:'ผิว'	,e:'skin; complexion; surface'},
{t:'ผี'	,e:'ghost; spirit'},
{t:'ผู้'	,e:'person, human, one (who...); [Thai prefix corresponding to the English suffixes] \'-er\' or \'-or\''},
{t:'ผูก'	,e:'to bind; tie; attach'},
{t:'เผย'	,e:'to open; to disclose; to discover; to unveil; to uncover; to reveal'},
{t:'เผื่อ'	,e:'in case of; provided that; if; for; in case (that)'},
{t:'แผ่'	,e:'expand; spread out'},
{t:'แผน'	,e:'plan; pattern; scheme; project; model'},
{t:'แผ่น'	,e:'sheet; tablet; plank; strip; piece'},
{t:'แผ่นดิน'	,e:'land; country; kingdom; ground; earth; plot of land'},
{t:'ฝน'	,e:'rain'},
{t:'ฝรั่ง'	,e:'non-Asian foreigner, [usually] Caucasian [see notes]'},
{t:'ฝัก'	,e:'hull; pod; sheath; case; nutshell'},
{t:'ฝัง'	,e:'to bury; inter; put in the ground; implant'},
{t:'ฝา'	,e:'lid or cover of a pot or bowl; cap'},
{t:'ฝาก'	,e:'to deposit; leave; entrust (something); consign'},
{t:'ฝ่าย'	,e:'side; party; faction; group'},
{t:'ฝึก'	,e:'to drill; to train; to practice; to exercise; to teach'},
{t:'ฝึกหัด'	,e:'to drill; practice; rehearse; to train'},
{t:'พงศาวดาร'	,e:'annals; historical record; pedigree; chronicle; dynastic history'},
{t:'พ้น'	,e:'to pass by; to be beyond; to be clear of'},
{t:'พ้น'	,e:'in the clear; safe from'},
{t:'พบ'	,e:'to meet or rendezvous; locate; find; encounter; experience; discover'},
{t:'พม่า'	,e:'Burma; Burmese'},
{t:'พยาน'	,e:'witness'},
{t:'พยายาม'	,e:'to attempt; try; persevere; endeavor; make an effort'},
{t:'พรวน'	,e:'to break up into pieces; to loosen'},
{t:'พร้อม'	,e:'[is] ready; set; finished; complete'},
{t:'พร้อม'	,e:'in unison; concurrently; at the same time; fully'},
{t:'พระ'	,e:'priest; minister; cleric; monk; padre; god; Buddha image'},
{t:'พระ'	,e:'[a title or prefix word used with a most revered person, place, or object] royal'},
{t:'พระ'	,e:'[a title of ancient Thai civil nobility between พระยา (Phraya) and หลวง  (Luang)]'},
{t:'พระยา'	,e:'[title of ancient Thai civil nobility nobility between พระ  (Phra) and เจ้าพระยา  (Chao Phraya)]'},
{t:'พราหมณ์'	,e:'Brahman; an ancient religion'},
{t:'พฤศจิกายน'	,e:'November'},
{t:'พฤษภาคม'	,e:'May'},
{t:'พฤหัสบดี'	,e:'[formal, general] Jupiter'},
{t:'พล'	,e:'power; force; strength; violence; military force'},
{t:'พล'	,e:'low member of military or police force'},
{t:'พล'	,e:'general; General [military rank]'},
{t:'พลเมือง'	,e:'a citizen; an inhabitant; people; population'},
{t:'พลอย'	,e:'gem; gems; gemstones; jewels; jewelry'},
{t:'พลิก'	,e:'to turn over; to roll from side to side; to play tricks with; to twist'},
{t:'พวก'	,e:'[of people, animals] a group, a party'},
{t:'พอ'	,e:'[is] sufficient; [does] suffice; [is] adequate; enough'},
{t:'พ่อ'	,e:'father'},
{t:'พ้อง'	,e:'[is] synonymous; alike-sounding; identical; in agreement; coincident; simultaneous; allied'},
{t:'พัก'	,e:'to halt, lay-over, stop for the night, stay overnight at a place, to rest or relax, remain at a place temporarily'},
{t:'พัก'	,e:'a short while'},
{t:'พัน'	,e:'thousand; the number one thousand (1,000)'},
{t:'พันธ์'	,e:'to be related, to bind, to fasten together'},
{t:'พา'	,e:'to bring; take; head a procession; lead the way; conduct; show the way; carry; lead people or animals; take along'},
{t:'พาณิชย์'	,e:'commerce; pertaining to commerce'},
{t:'พาย'	,e:'to row; to paddle'},
{t:'พาล'	,e:'to fight or quarrel with, accost, pick a fight with, to bully'},
{t:'พาหนะ'	,e:'vehicle; carrier; transport'},
{t:'พิจารณา'	,e:'to consider; to appraise; to study; to examine; to investigate; to reckon'},
{t:'พิธี'	,e:'ceremony; event'},
{t:'พิมพ์'	,e:'to print; type; importing; make an impression of'},
{t:'พิเศษ'	,e:'[is] special; particular; unique; extraordinary; extra'},
{t:'พิเศษ'	,e:'distinction; uniqueness; peculiarity; oddity'},
{t:'พิษ'	,e:'poison; toxin; venom'},
{t:'พี่'	,e:'older sibling; older siblings'},
{t:'พึง'	,e:'[written] should; ought; ought to'},
{t:'พึ่ง'	,e:'just now; a moment ago; recently'},
{t:'พืช'	,e:'plant; vegetation; fauna; seedling'},
{t:'พื้น'	,e:'ground; land; foundation'},
{t:'พื้น'	,e:'[of a room] floor; foundation; slab; underfloor'},
{t:'พุทธ'	,e:'Buddha'},
{t:'พุธ'	,e:'[general] Mercury'},
{t:'พูด'	,e:'to speak; to talk; to say'},
{t:'เพราะ'	,e:'because; because of; due to; owing to'},
{t:'เพลิง'	,e:'fire; blaze; flame; conflagration'},
{t:'เพลิน'	,e:'to enjoy'},
{t:'เพลิน'	,e:'joyful; joyous; jovial; enjoyable; pleasurable; carried away'},
{t:'เพาะ'	,e:'to culture (germs); to cultivate; to plant; to build (body)'},
{t:'เพิ่ม'	,e:'to increase; add; grow; advance; boost; develop; enlarge; enhance; escalate; expand; extend; multiply; raise; spread; swell'},
{t:'เพียง'	,e:'only; merely; up until the point; as much as; as far as; till; just until'},
{t:'เพียงไร'	,e:'how many'},
{t:'เพียน'	,e:'to add to, to augment, to supplement'},
{t:'เพื่อ'	,e:'for the purpose of...'},
{t:'เพื่อน'	,e:'friend; pal; chum; buddy; older colleague'},
{t:'แพ้'	,e:'allergic to; have an allergy to'},
{t:'แพ้'	,e:'[is] defeated; lost'},
{t:'แพ้'	,e:'be defeated (by); to lose (to); to fail'},
{t:'แพง'	,e:'[is] expensive'},
{t:'ฟ้อง'	,e:'to accuse; prosecute'},
{t:'ฟ้อง'	,e:'to sue'},
{t:'ฟัก'	,e:'gourd; squash Cucurbita'},
{t:'ฟัง'	,e:'to listen; listen to'},
{t:'ฟัน'	,e:'tooth'},
{t:'ฟ้า'	,e:'the sky; firmament; heaven'},
{t:'ไฟ'	,e:'fire; flame'},
{t:'ไฟ'	,e:'electric light; light switch'},
{t:'ภรรยา'	,e:'wife'},
{t:'ภัย'	,e:'harm; danger; catastrophe; fear; dread; peril'},
{t:'ภาค'	,e:'section, portion, part [I, II, III, etc., of a movie or novel], region, division, side, segment, share, period, time'},
{t:'ภาพ'	,e:'image; picture; drawing; vision'},
{t:'ภาพ'	,e:'existence; state; being; [a suffix corresponding to the English suffix "-dom"]'},
{t:'ภาย'	,e:'[referring to placement in space or time] location'},
{t:'ภายนอก'	,e:'[is] outside; external'},
{t:'ภายใน'	,e:'the inside, the interior'},
{t:'ภายใน'	,e:'within; by (a certain time frame)'},
{t:'ภายใน'	,e:'internal; inside'},
{t:'ภายหลัง'	,e:'afterward; later; afterwards'},
{t:'ภาษา'	,e:'language(s); speech; idiom; tongue; lingo; understanding; words'},
{t:'ภาษิต'	,e:'saying; proverb; motto; saw; teaching; maxim; adage'},
{t:'ภาษี'	,e:'tax; duty'},
{t:'ภูเขา'	,e:'hill; mountain'},
{t:'ภูมิ'	,e:'status; standing'},
{t:'ภูมิ'	,e:'earthen land; soil; site; grounds; floor; place'},
{t:'ภูมิ'	,e:'[is] grand; proud; dignified'},
{t:'มกราคม'	,e:'January'},
{t:'มณฑล'	,e:'precinct; administrative region'},
{t:'มนตรี'	,e:'a high government official or adviser, a mandarin'},
{t:'มนุษย์'	,e:'human being; man; human; homo sapiens'},
{t:'มอง'	,e:'to look at; to see; to stare at; to glance; to eye'},
{t:'มอญ'	,e:'Mon, Pegu, Peguan; an ethnic group of Burma and Thailand'},
{t:'มอบ'	,e:'to assign; entrust; turn over; commit; deliver'},
{t:'มัก'	,e:'often; frequently; inclined towards; prone towards'},
{t:'มั่งมี'	,e:'[is] rich; wealthy; affluent; opulent'},
{t:'มัธยม'	,e:'secondary education; high school'},
{t:'มัน'	,e:'[the indefinite pronoun for referring to animals or things] it; they'},
{t:'มัน'	,e:'oil; fat; grease'},
{t:'มั่นคง'	,e:'[is] secure; stable; firm; solid; sturdy'},
{t:'มา'	,e:'to come; <subject> comes'},
{t:'ม้า'	,e:'horse'},
{t:'มาก'	,e:'much; many; very; more; so much; a great deal; seriously'},
{t:'มากมาย'	,e:'very much; plentiful; much; many; countless; various; several; a lot of; many; diversified; miscellaneous; numerous'},
{t:'มารดา'	,e:'mother'},
{t:'มิตร'	,e:'friend or friends'},
{t:'มิถุนายน'	,e:'June'},
{t:'มี'	,e:'to have or possess; to be available'},
{t:'มีด'	,e:'knife'},
{t:'มีนาคม'	,e:'March'},
{t:'มือ'	,e:'hand; hands'},
{t:'มุ่งหมาย'	,e:'to aim at or for; to intend; to mean; to endeavor; to attempt'},
{t:'เมฆ'	,e:'cloud'},
{t:'เมตตา'	,e:'[Buddhism] goodwill; kindness; mercy; clemency; compassion; kindheartedness'},
{t:'เมล็ด'	,e:'seed; grain; tiny piece; bean'},
{t:'เมษายน'	,e:'April'},
{t:'เมา'	,e:'[is] drunk; intoxicated; inebriated; dizzy; sick; [has] nausea'},
{t:'เมีย'	,e:'wife'},
{t:'เมื่อ'	,e:'[indicating a point in time] when; on (a date)'},
{t:'เมื่อไร'	,e:'[used in a question] when'},
{t:'เมือง'	,e:'city; nation; country; land; town'},
{t:'แม่'	,e:'[general] mother'},
{t:'แม่น้ำ'	,e:'river'},
{t:'แม้'	,e:'though; if; provided; even; even if'},
{t:'แมลง'	,e:'bug; insect'},
{t:'แมว'	,e:'cat'},
{t:'ไม่'	,e:'not; no'},
{t:'ไม้'	,e:'wood; woods; forest; stick; rod'},
{t:'ไมตรี'	,e:'amicability; friendship; goodwill; (to be on) good terms'},
{t:'ยก'	,e:'to raise; to hoist (up); to revoke; to advance; to abolish; to elevate; to lift; to erect'},
{t:'ยนต์'	,e:'[is] powered; motorized; mechanical'},
{t:'ยอด'	,e:'top; pinnacle; tip; peak; summit; crown; zenith'},
{t:'ยอด'	,e:'excellent; superb; perfect; great'},
{t:'ยอด'	,e:'budgetary item; grand total; total'},
{t:'ยอม'	,e:'to allow, yield, let, accept, agree to; is willing to'},
{t:'ย่อม'	,e:'can; naturally; as a matter of course; inevitably'},
{t:'ยัง'	,e:'yet; since; not yet; still'},
{t:'ยา'	,e:'drug; medicine; remedy; medication; having to do with medical treatment'},
{t:'ยาก'	,e:'[is] difficult; hard; not easy'},
{t:'ยาม'	,e:'a guard, sentry, sentinel or night watchman'},
{t:'ยาม'	,e:'period of time designated as a shift or a watch for a sentinel or watchman'},
{t:'ย้าย'	,e:'to move or transfer'},
{t:'ยาว'	,e:'[of geometric length] [is] long'},
{t:'ยิง'	,e:'to fire or shoot (a gun)'},
{t:'ยิ่ง'	,e:'excessive; extreme'},
{t:'ยิ่ง'	,e:'excessively; extremely; very much; even more so'},
{t:'ยืน'	,e:'to stand'},
{t:'ยุง'	,e:'mosquito'},
{t:'ยุติธรรม'	,e:'[is] fair; just'},
{t:'ยุโรป'	,e:'[Thai transcription of the foreign loanword] Europe'},
{t:'เย็น'	,e:'[of an object, atmosphere, liquid, or time of day] [is] cool; cold'},
{t:'แยก'	,e:'intersection'},
{t:'แย่ง'	,e:'to catch; to seize; to scramble for; contend for; compete for; wrest'},
{t:'โยน'	,e:'to throw; pitch; cast; fling; hurl'},
{t:'รถ'	,e:'car; vehicle; bus'},
{t:'รบ'	,e:'to go to war; to fight; to make war; to battle'},
{t:'ร่ม'	,e:'umbrella; parasol'},
{t:'ร่ม'	,e:'shade; sunshade; screen; blind; canopy; cover; covering; curtain; shield; veil'},
{t:'รวม'	,e:'to combine; collect; add; include; incorporate; assemble; confederate'},
{t:'ร่วม'	,e:'to share; join; partake; participate; unite; affiliate with; associate with; team with'},
{t:'รอง'	,e:'to support (from below); to place (something) under'},
{t:'รอง'	,e:'to collect (liquid) under (a spout)'},
{t:'รอง'	,e:'[of ranking and order] deputy, vice-; subordinate; associate; secondary, [competition, status of wife] second, next'},
{t:'รองเท้า'	,e:'shoe or shoes; footwear; boot or boots'},
{t:'ร้อง'	,e:'cry out; to scream; to exclaim; to weep; to sob; to yell; to roar; to squeal'},
{t:'ร้อน'	,e:'[of temperature] [is] hot'},
{t:'รอบ'	,e:'cycle; round; circuit; trip; anniversary; revolution'},
{t:'รอย'	,e:'a trace; pathway; track; vestige; impression; imprint; a mark'},
{t:'ร้อย'	,e:'hundred; the number one hundred; 100'},
{t:'ระงับ'	,e:'to halt; to curb; to stop; cease; mitigate; check suppress; repress'},
{t:'ระเบียบ'	,e:'order; regulations; system'},
{t:'ระยะ'	,e:'a space; interval or separation (as in punctuation); a period; a stage; distance; time'},
{t:'ระลึก'	,e:'to think of; to recollect; to recall; to remember'},
{t:'ระหว่าง'	,e:'between; in the middle of; the middle; among'},
{t:'รัก'	,e:'to love; <subject> loves'},
{t:'รักษา'	,e:'to take care of; maintain; save'},
{t:'รักษา'	,e:'to remedy, treat, or cure an illness'},
{t:'รัง'	,e:'nest; home'},
{t:'รัฐบาล'	,e:'government'},
{t:'รับ'	,e:'to receive, get; accept; catch a thrown object, take, to fetch, to pick (someone) up, (colloq.) telephone call'},
{t:'รับประทาน'	,e:'to dine; eat; sup; have a meal'},
{t:'ราก'	,e:'root; foundation; source'},
{t:'ราคา'	,e:'price; tariff; fare; cost; [coinage] denomination'},
{t:'ราง'	,e:'groove; conduit; rail; track'},
{t:'ร่าง'	,e:'shape; figure; body; outline; form'},
{t:'ร่าง'	,e:'mesh; structure; grid'},
{t:'รางวัล'	,e:'award; prize; reward'},
{t:'ราชการ'	,e:'civil service; public service; government service; bureaucracy'},
{t:'ราชา'	,e:'royal, of or pertaining to king'},
{t:'ร้าน'	,e:'store or shop; commercial establishment; a place where merchandise is sold'},
{t:'ราย'	,e:'list of items; record; tally; story; account; item; statement; case'},
{t:'ร้าย'	,e:'[is] bad; very bad; fierce; cruel; harmful; evil; wild'},
{t:'ราว'	,e:'handrail; railing; rod; rack'},
{t:'ราษฎร์'	,e:'citizens; population; the people; the populace; the masses'},
{t:'รำ'	,e:'to dance'},
{t:'ริม'	,e:'edge; rim; banks (of a river or canal)'},
{t:'ริม'	,e:'by; beside; alongside; at the side of'},
{t:'รีบ'	,e:'to hurry'},
{t:'รุ่ง'	,e:'dawn; daybreak'},
{t:'รู'	,e:'tiny hole; cavity; gap'},
{t:'รู้'	,e:'to know a subject or piece of learned information'},
{t:'รู้จัก'	,e:'[of a person, place, or idea] to know'},
{t:'รู้สึก'	,e:'to feel or emote, to feel an emotion; to experience'},
{t:'รูป'	,e:'shape; form; contour; appearance; similarity-to'},
{t:'เร็ว'	,e:'[is] fast; quick; speedy'},
{t:'เรา'	,e:'we; us; our'},
{t:'เริ่ม'	,e:'to begin; to start; commence'},
{t:'เรียก'	,e:'to call out; called; to be named'},
{t:'เรียง'	,e:'to arrange; place in order; line up'},
{t:'เรียน'	,e:'to study at the elementary school level'},
{t:'เรียบร้อย'	,e:'[is] neat; ready; all set; all in order; orderly; tidy'},
{t:'เรียบร้อย'	,e:'[is] polite and well mannered'},
{t:'เรือ'	,e:'boat; ship; barge; vessel'},
{t:'เรื่อง'	,e:'about; relating to; concerning; [as part of the header in an official letter along with เรียน ] "Subject:"'},
{t:'เรือน'	,e:'household; dwelling; abode; [typically a] wooden house'},
{t:'แรก'	,e:'[is] first; primary; initial'},
{t:'แรง'	,e:'[is] strong; powerful; energetic; having energy; hard'},
{t:'โรค'	,e:'disease; sickness; case'},
{t:'โรง'	,e:'building; hall; pavilion; structure; theater'},
{t:'โรงเรียน'	,e:'[general] school [not used to refer to college or university]'},
{t:'ไร'	,e:'[suffix indicating qualification, quantification, or interrogation, as indicated below]'},
{t:'ไร่'	,e:'the rai, a unit of land measure'},
{t:'ไร้'	,e:'[is] without; lacking; devoid of; in need of'},
{t:'ลง'	,e:'to come down; go down; get off; get out of; descend; land'},
{t:'ลด'	,e:'to decrease; reduce; lower; diminish; lessen'},
{t:'ลบ'	,e:'to erase'},
{t:'ลบ'	,e:'mathematical subtraction; minus'},
{t:'ลบ'	,e:'[charge, digit] negative; non-positive'},
{t:'ลม'	,e:'air; wind; storm'},
{t:'ล้ม'	,e:'to fall down'},
{t:'ลวง'	,e:'to deceive; to gull; to dupe; to impose upon by craftiness or guile; to lure; entice or tempt into some snare or trap'},
{t:'ล่วง'	,e:'to exceed; overstep; pass; to go beyond'},
{t:'ล้วน'	,e:'[is] pure; absolute; pristine'},
{t:'ลอง'	,e:'to try; test; to experiment with; to try out'},
{t:'ลอย'	,e:'to float, to set afloat or adrift; to waft through (the air)'},
{t:'ละ'	,e:'each; every; one at a time; [implying division] per'},
{t:'ละคร'	,e:'[general] theatrical presentation'},
{t:'ละลาย'	,e:'to dissolve; melt'},
{t:'ละออง'	,e:'dust; spray; mist; particles; fine particles; powder; fall-out'},
{t:'ละเอียด'	,e:'[is] detailed; exact; delicate; fine; powdered; finely powdered; meticulous; careful; thorough; methodical'},
{t:'ลัก'	,e:'to steal; to pilfer; to pinch; to carry off'},
{t:'ลักษณะ'	,e:'characteristic; form; attribute; quality; pattern; style'},
{t:'ลา'	,e:'to say good-bye; to be on leave; to take one\'s leave; to bid farewell'},
{t:'ลาก'	,e:'to drag; pull at; haul'},
{t:'ล่าง'	,e:'below; under; down below; underneath'},
{t:'ล้าง'	,e:'to clean; wash; rinse'},
{t:'ล้าน'	,e:'million; the number one million (1,000,000)'},
{t:'ลำดับ'	,e:'sequence; order; line; arrangement; series'},
{t:'ลำบาก'	,e:'[is] difficult; hard; troublesome'},
{t:'ลำพัง'	,e:'individual; private; personal'},
{t:'ลิง'	,e:'monkey'},
{t:'ลิ้น'	,e:'tongue'},
{t:'ลึก'	,e:'[is] deep'},
{t:'ลืม'	,e:'to forget'},
{t:'ลุก'	,e:'to rise; stand up; get up; arise'},
{t:'ลุง'	,e:'uncle; elder uncle; elder brother of a parent; great uncle'},
{t:'ลูก'	,e:'child; offspring; son or daughter [including figurative usage for certain ideas]'},
{t:'เล็ก'	,e:'[is] small; tiny; fine; little'},
{t:'เล่น'	,e:'to play; have fun; enjoy; amuse; jest'},
{t:'เล่ม'	,e:'[of a book] a volume'},
{t:'เลย'	,e:'[used for emphasis at the end of a statement] "...at all." — "...so much!" — "...extremely!; completely, directly; simply, without doing anything else first; right away'},
{t:'เลว'	,e:'[is] bad; inferior; worthless; base; vile'},
{t:'เล่า'	,e:'to relate a story; to tell; to recount; to narrate'},
{t:'เลิก'	,e:'to quit; to stop; to give up; cancel; suspend; discontinue; abolish; cease; exit'},
{t:'เลิก'	,e:'separate from another person; to break up a relationship'},
{t:'เลี้ยง'	,e:'to feed; nourish; nurture; raise a child or animal; provide for; rear; bring up; foster; nurse'},
{t:'เลี้ยง'	,e:'to have a banquet; to hold a party or feast'},
{t:'เลี้ยว'	,e:'to turn; make a change in direction'},
{t:'เลือก'	,e:'to select or choose; elect; pick'},
{t:'เลื่อน'	,e:'to slide; to slip; to glide; to skid'},
{t:'เลื่อน'	,e:'to postpone'},
{t:'เลื่อน'	,e:'to promote'},
{t:'แล'	,e:'to look at; to watch; to see; to glance; to take a look'},
{t:'แล้ง'	,e:'[is] dry'},
{t:'แล่น'	,e:'to move; to run; to sail; to glide; to slide; to steam'},
{t:'แล้ว'	,e:'[adverbial word indicating past tense or aspect marker indicating present perfect (past continued to present)] in the past; completed; still; to make done'},
{t:'และ'	,e:'and'},
{t:'โลก'	,e:'the planet Earth'},
{t:'โลก'	,e:'the world; globe'},
{t:'วงศ์'	,e:'lineage; family; dynasty; clan; kinship; descent; stock; race; multitude; assemblage; family [taxonomy]'},
{t:'วัง'	,e:'palace'},
{t:'วัด'	,e:'temple; monastery'},
{t:'วัน'	,e:'day'},
{t:'วันจันทร์'	,e:'Monday'},
{t:'วันพฤหัสฯ'	,e:'[colloquial] Thursday'},
{t:'วันพุธ'	,e:'Wednesday'},
{t:'วันศุกร์'	,e:'Friday'},
{t:'วันเสาร์'	,e:'Saturday'},
{t:'วันอังคาร'	,e:'Tuesday'},
{t:'วันอาทิตย์'	,e:'Sunday'},
{t:'วัว'	,e:'cow; ox; bovine'},
{t:'ว่า'	,e:'to speak; say; aver; think'},
{t:'วาง'	,e:'to lay down; to put down; to put on (airs); to deposit; to place; to set down'},
{t:'ว่าง'	,e:'[is] vacant; free; available; empty'},
{t:'วาจา'	,e:'speech; words; utterance; remarks; statements'},
{t:'วาน'	,e:'the day before'},
{t:'วิ่ง'	,e:'to run; <subject> runs'},
{t:'วิชา'	,e:'[of study] a subject; knowledge; branch of study'},
{t:'วิทยา'	,e:'science; knowledge; learning; philosophy'},
{t:'วิธี'	,e:'method; way; mode of operation; procedure'},
{t:'เว้น'	,e:'to exclude; omit; skip over'},
{t:'เวลา'	,e:'[general] time [as in space and time]'},
{t:'ศาสนา'	,e:'religion; creed'},
{t:'ศุกร์'	,e:'[general] Venus'},
{t:'ศูนย์'	,e:'zero; the number or quantity zero'},
{t:'ส่ง'	,e:'to ship; send or deliver (mail or parcel or package); emit'},
{t:'สงคราม'	,e:'war; battle; hostilities; conflict; combat'},
{t:'สงสัย'	,e:'to doubt; suspect; wonder about'},
{t:'สงสัย'	,e:'[is] suspicious'},
{t:'สงสาร'	,e:'feel sorry for; to pity'},
{t:'สด'	,e:'[is] fresh; green; not spoiled; new; newly produced or minted; raw; [colors] bright'},
{t:'สตรี'	,e:'female; woman; lady'},
{t:'สตางค์'	,e:'sadang, a Thai coin worth one one-hundredth of a Baht; [figuratively meaning] money [in a general sense]'},
{t:'สติ'	,e:'mindfulness; consciousness; mind; thought; sense; sensibility; sense of responsiveness; attention; attentiveness; reflection; balance'},
{t:'สถาน'	,e:'place; site; location; locality'},
{t:'สถานี'	,e:'station'},
{t:'สนใจ'	,e:'[is] interested (in); [is] attentive (to)'},
{t:'สนาม'	,e:'field; park; lawn; playground; meadow; yard; turf; grassy field'},
{t:'สนุก'	,e:'[is] fun; enjoyable; entertaining; amusing; pleasant'},
{t:'สบาย'	,e:'[is] happy; comfortable; content; fine; well; cool; o.k.; good; nice'},
{t:'สภา'	,e:'council; assembly'},
{t:'สม'	,e:'[is] becoming; suitable for; appropriate; conforming; worthy of'},
{t:'สม'	,e:'to deserve; to meet with'},
{t:'ส้ม'	,e:'[general] orange; citrus; orange color'},
{t:'สมควร'	,e:'[is] suitable; proper; fitting; reasonable; appropriate; correct'},
{t:'สมเด็จ'	,e:'abbot, great one, a title of high rank for a queen and highly revered Buddhist priests'},
{t:'สมบัติ'	,e:'assets; treasure; fortune; riches; wealth'},
{t:'สมมุติ'	,e:'to assume; suppose'},
{t:'สมัย'	,e:'era; times; period; age'},
{t:'สมาคม'	,e:'association; organization; corporation'},
{t:'สมาชิก'	,e:'member; subscriber'},
{t:'สรรเสริญ'	,e:'to praise; admire; laud'},
{t:'สระ'	,e:'a vowel'},
{t:'สร้าง'	,e:'to build; construct; create; establish; to cause'},
{t:'สละ'	,e:'to abandon; to renounce; to relinquish; to sacrifice; to foresake; to abdicate'},
{t:'สลึง'	,e:'salueng; 25 sadang; ¼ of 1 baht'},
{t:'สวน'	,e:'garden; field; park; farm; plantation'},
{t:'สวม'	,e:'to wear; to put on; to dress with; to cover; to clothe'},
{t:'สวย'	,e:'[is] beautiful; pretty; lovely; gorgeous; attractive; nice-looking [usually referring to women but also possibly a view]'},
{t:'สวรรค์'	,e:'heaven; paradise'},
{t:'สวัสดีครับ'	,e:'[spoken politely by a male] hello; goodbye'},
{t:'สวัสดีค่ะ'	,e:'[spoken politely by a female] hello or goodbye'},
{t:'สว่าง'	,e:'[is] bright; shining; illuminated'},
{t:'สหาย'	,e:'friend, companion, pal'},
{t:'สอง'	,e:'two; the number or quantity two'},
{t:'ส่อง'	,e:'to look at with a telescope, microscope, or binoculars'},
{t:'ส่อง'	,e:'to look in a mirror'},
{t:'ส่อง'	,e:'to illuminate, enlighten; to shine or throw light upon'},
{t:'สอน'	,e:'to teach; to instruct; to train'},
{t:'สะดวก'	,e:'[is] convenient; comfortable'},
{t:'สะพาน'	,e:'bridge; pier'},
{t:'สะอาด'	,e:'[is] clean; spotless'},
{t:'สัก'	,e:'to tattoo'},
{t:'สัก'	,e:'[general] [is] teak'},
{t:'สั่ง'	,e:'to order merchandise, food, or medicine'},
{t:'สังเกต'	,e:'to notice; to observe; to perceive; to recconoiter; to make a note of'},
{t:'สัญญา'	,e:'legal contract; promise; agreement; treaty; pact; deal'},
{t:'สัตว์'	,e:'an animal; animals'},
{t:'สั้น'	,e:'[of length] [is] short; squat'},
{t:'สัมมา'	,e:'right; correct; honest; virtuous; righteous'},
{t:'สาม'	,e:'three; the number or quantity three'},
{t:'สามารถ'	,e:'[is] capable; able'},
{t:'สามี'	,e:'husband'},
{t:'สาย'	,e:'wire; line; rope; string; strap; connection; tie'},
{t:'สาว'	,e:'young woman; girl; unmarried woman; maiden; damsel; lass; lassie (informal); maid; virgin; wench'},
{t:'สำนัก'	,e:'office; bureau; institute; institution'},
{t:'สำราญ'	,e:'[is] content happy; reveling (in)'},
{t:'สำเร็จ'	,e:'to succeed; finish; complete; accomplish'},
{t:'สำหรับ'	,e:'for; as for; in order to; for the purpose of; in order that'},
{t:'สิ่ง'	,e:'[general term for] a thing; item'},
{t:'สิงโต'	,e:'lion'},
{t:'สิงหาคม'	,e:'August'},
{t:'สิน'	,e:'property; wealth; riches; possessions'},
{t:'สินค้า'	,e:'merchandise; product; finished good'},
{t:'สิบ'	,e:'ten; the number or quantity ten'},
{t:'สี'	,e:'color; colors; paint'},
{t:'สี่'	,e:'four; the number or quantity four'},
{t:'สืบ'	,e:'to search for the facts; to investigate; to detect; to trace; to track'},
{t:'สืบ'	,e:'to succeed; to pass on to another; to continue; to advance'},
{t:'สุข'	,e:'happiness; content; bliss; pleasure'},
{t:'สู้'	,e:'to contend; fight; compete; make an aggressive move'},
{t:'สู้'	,e:'to face; to be against'},
{t:'สูง'	,e:'[is] tall; high; advanced'},
{t:'เสด็จ'	,e:'[royal use only] to come or go, describing the movement of a Royal person'},
{t:'เส้น'	,e:'geometric line; string; filament; thread; rope; cord; route or routing; ply'},
{t:'เสนาบดี'	,e:'secretary of state; minister; commander in chief'},
{t:'เสมอ'	,e:'[is] even; level; flush'},
{t:'เสมียน'	,e:'clerk; secretary'},
{t:'เสร็จ'	,e:'[is] finished; completed; ready'},
{t:'เสาร์'	,e:'[general] Saturn'},
{t:'เสีย'	,e:'[is] spent; broken; wasted; malfunctioning; defective; out of order; rotten; bad'},
{t:'เสียใจ'	,e:'[is] very sorry; grieving'},
{t:'เสียง'	,e:'tone; sound; volume; noise'},
{t:'เสือ'	,e:'tiger'},
{t:'เสื้อ'	,e:'shirt; blouse; jacket'},
{t:'เสื่อม'	,e:'to deteriorate; to depreciate; decrease; decline'},
{t:'แสง'	,e:'light; ray; light ray; beam of light'},
{t:'แสดง'	,e:'to act; perform; demonstrate; show; or display'},
{t:'แสวง'	,e:'to pursue; seek; look for; search out'},
{t:'ใส'	,e:'[is] clear; transparent'},
{t:'ใส่'	,e:'to put in; add'},
{t:'ไส'	,e:'to push forward; to shove; to thrust'},
{t:'หก'	,e:'six; the number or quantity six'},
{t:'หญิง'	,e:'female'},
{t:'หนทาง'	,e:'way; route; course; path'},
{t:'หน่อย'	,e:'[word used to soften the meaning of a sentence] "...a bit" — "...somewhat" — "...to some extent"; this little thing, no big deal here, for just a moment'},
{t:'หนัก'	,e:'[is] heavy; laden; fully loaded; weighing'},
{t:'หนัก'	,e:'[of a medical condition or other problem] [is] serious'},
{t:'หนัง'	,e:'cinema; film; movie'},
{t:'หนังสือ'	,e:'book; document; letters; alphabet; printed document; written document'},
{t:'หนา'	,e:'[is] thick; (of fabric) heavy'},
{t:'หน้า'	,e:'face; front; facade; visage; (to nod) head'},
{t:'หน้าที่'	,e:'duty; function; obligation; responsibility'},
{t:'หนาว'	,e:'[feeling] [is] cool; cold'},
{t:'หนี'	,e:'to escape; elope; hurry away; flee'},
{t:'หนี้'	,e:'debt; liability'},
{t:'หนึ่ง'	,e:'one; the number or quantity one'},
{t:'หนุ่ม'	,e:'teenage male; young man; adolescent'},
{t:'หนู'	,e:'mouse; mice; rat'},
{t:'ห่ม'	,e:'to cover; clothe; wrap; enclose; dress'},
{t:'ห่ม'	,e:'cover; close'},
{t:'หมด'	,e:'[is] empty; finished; all used up; complete; lost'},
{t:'หมวก'	,e:'hat; cap'},
{t:'หมอ'	,e:'[informal] a medical doctor; a fortuneteller; a shaman'},
{t:'หม้อ'	,e:'small container'},
{t:'หม้อ'	,e:'a pot for cooking'},
{t:'หมอก'	,e:'fog; mist; foggy; misty'},
{t:'หมา'	,e:'dog'},
{t:'หมาย'	,e:'warrant; notice; order; point; writ; summons; decree'},
{t:'หมี'	,e:'bear (the animal)'},
{t:'หมุน'	,e:'to dial; turn; revolve; spin; rotate; whirl'},
{t:'หมู'	,e:'pork; meat of the pig'},
{t:'หมู่'	,e:'group; race; flock; herd; crowd; corporation; company; collection; squad; clusters; series; class; genus; rove'},
{t:'หมู่'	,e:'Moo [part of a street address in Thailand]; neighborhood; block'},
{t:'หยด'	,e:'[of liquid] a drop'},
{t:'หยด'	,e:'to drip'},
{t:'หยาบ'	,e:'[is] crude; coarse; rough; rugged'},
{t:'หยาบ'	,e:'[is] rude; vulgar; impolite; obscene'},
{t:'หยุด'	,e:'to stop; halt'},
{t:'หรือ'	,e:'or'},
{t:'หลวง'	,e:'[is] royal; of the court; superior; official; great'},
{t:'หลวง'	,e:'state (pertaining to the government)'},
{t:'หลัก'	,e:'post; pillar; pole; stake; lingam'},
{t:'หลัก'	,e:'basis; foundation; principle; maxim; doctrine; tenet'},
{t:'หลัง'	,e:'behind; following; at the rear'},
{t:'หลับ'	,e:'to shut; sleep; to be asleep; go to bed'},
{t:'หลาน'	,e:'grandchild'},
{t:'หลาย'	,e:'several; numerous; a variety; many; sundry; diverse; [the prefix] "multi-"'},
{t:'หลีก'	,e:'to avoid; evade; dodge; get out of the way'},
{t:'หลุม'	,e:'hole; hole in the ground; pit'},
{t:'หวัง'	,e:'to hope; to expect; to want'},
{t:'หวาน'	,e:'[is] sweet'},
{t:'ห้อง'	,e:'room of a building; apartment; chamber'},
{t:'หัก'	,e:'to break; be broken off; reflect; tax'},
{t:'หัด'	,e:'to train; practice; drill or exercise; make proficient; learn to'},
{t:'หัด'	,e:'measles; rubseola, a highly contageous skin disease'},
{t:'หัน'	,e:'to turn oneself around; to face in a direction'},
{t:'หัว'	,e:'head; brain; bulb; tuber'},
{t:'หา'	,e:'to find; look for; seek; to search'},
{t:'ห้า'	,e:'five; the number or quantity five'},
{t:'หาก'	,e:'allowing that; if; despite; rather'},
{t:'หาง'	,e:'tail'},
{t:'ห่าง'	,e:'[is] distant; far from; far away; far apart'},
{t:'หาด'	,e:'beach'},
{t:'ห้าม'	,e:'[is] forbidden; taboo; prohibited; banned'},
{t:'หาย'	,e:'to disappear; lose; lost; be missing'},
{t:'หู'	,e:'ear'},
{t:'เห็น'	,e:'to see; visualize'},
{t:'เหมือน'	,e:'[is] similar; all the same; like; as'},
{t:'เหลน'	,e:'great-grandchild'},
{t:'แหล่ะ'	,e:'[a colloquial particle used to emphasize what precedes it]'},
{t:'ให้'	,e:'to give; to let; to send to; to allow; to convey towards; to pay (attention); to have someone do something'},
{t:'ใหญ่'	,e:'[is] big; large; huge; major; enormous; extensive; sizeable'},
{t:'ใหม่'	,e:'[is] new; modern; fresh'},
{t:'ไหน'	,e:'[used as a question] which; where; when'},
{t:'ไหม'	,e:'[word added at the end of a statement to indicate a question]'},
{t:'ไหม้'	,e:'to burn'},
{t:'ไหล'	,e:'[as a liquid] to flow or run, to slither'},
{t:'อก'	,e:'[general] breast; chest'},
{t:'อด'	,e:'to abstain (from food, e.g.); fast; refrain; cease'},
{t:'อธิบาย'	,e:'to explain; define; describe'},
{t:'อนุญาต'	,e:'to give permission or license, permit, allow, grant, consent'},
{t:'อเมริกา'	,e:'America; United States; American'},
{t:'อยาก'	,e:'[auxiliary verb] to want; desire; crave for'},
{t:'อย่าง'	,e:'variety; style; pattern; type; kind; sort; mode; manner; method'},
{t:'อยู่'	,e:'is (located at); to reside; to live (at)'},
{t:'อวด'	,e:'to boast; brag; show off; display'},
{t:'อ้วน'	,e:'[is] fat; overweight; not thin'},
{t:'ออก'	,e:'the exit; the way out'},
{t:'อ่อน'	,e:'[is] soft; pliable; tender'},
{t:'ออม'	,e:'to conserve; save; economize'},
{t:'อะไร'	,e:'[indicating a question] what'},
{t:'อักษร'	,e:'alphabet; [of the alphabet:] letter; character; glyph; word; sound; vowels; consonants'},
{t:'อังกฤษ'	,e:'England; English; Great Britain; British'},
{t:'อัตรา'	,e:'rate; rating; criteria; established scale; limit; standard; class; grade; standing'},
{t:'อัน'	,e:'item; a small thing; piece'},
{t:'อันตราย'	,e:'[is] dangerous; harmful; evil'},
{t:'อากาศ'	,e:'weather; air; climate'},
{t:'อ้าง'	,e:'to claim; claim that'},
{t:'อาจ'	,e:'[used with another verb to indicate possibility] may; might'},
{t:'อาณาเขต'	,e:'territory'},
{t:'อาณาจักร'	,e:'kingdom; jurisdiction; realm; domain; dominion'},
{t:'อาทิตย์'	,e:'week'},
{t:'อ่าน'	,e:'to read; <subject> reads'},
{t:'อาบน้ำ'	,e:'to bathe; take a bath; take a shower; swim'},
{t:'อาศัย'	,e:'to inhabit, live in, or dwell in a place, to reside'},
{t:'อาหาร'	,e:'food; meal; diet'},
{t:'อำนาจ'	,e:'authority; power'},
{t:'อำเภอ'	,e:'district; a subdivision of a Thai province'},
{t:'อีก'	,e:'again; after a time; still'},
{t:'อื่น'	,e:'[is] other'},
{t:'อุ้ม'	,e:'to carry; hold (in arms); to cradle'},
{t:'เอก'	,e:'[usually used as an adjective] [is] sole; solitary; single; chief; first; prime; important; leading; excellent; one; alone; lonely'},
{t:'เอง'	,e:'by oneself; on one\'s own; personally; myself; oneself; himself; themselves'},
{t:'เอา'	,e:'to desire; to want; to specify or order'},
{t:'เอา'	,e:'to take; get; bring'},
{t:'เอื้อเฟื้อ'	,e:'[is] considerate; helpful; generous; friendly'},
{t:'โอ'	,e:'pomelo citrus maxima'},
{t:'โอกาส'	,e:'chance; opportunity; occasion'},
{t:'โอรส'	,e:'one\'s own son (legitimate) used by royalty'},
];
